apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
    - name: app-name
      type: string
    - name: build-image
      type: string
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output
    
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: output
      params:
        - name: url
          value: "$(params.repo-url)"
      runAfter:
        - cleanup
    
    - name: lint
      taskRef:
        name: flake8-lint
      workspaces:
        - name: source
          workspace: output
      runAfter:
        - fetch-source
    
    - name: test
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output
      runAfter:
        - lint
    
    - name: build
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: output
      params:
        - name: IMAGE
          value: "$(params.build-image)"
      runAfter:
        - test
    
    - name: deploy
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) \
              --image=$(params.build-image) \
              --dry-run=client -o yaml | oc apply -f -
            oc expose svc/$(params.app-name)
      runAfter:
        - build